name: geopoint2
description: Geospatial data structures. Provides GeoPoint and GeoSerie models.
homepage: https://github.com/synw/geopoint
version: 0.9.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  extra_pedantic: ^1.3.0
  latlong2: ^0.8.0
  meta: ^1.3.0
  pedantic: ^1.11.0
  slugify: ^2.0.0

dev_dependencies:
  test: ^1.17.3
